STP Task/STP Task/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace STP_Task.Models
{
    public class LoginViewModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

STP Task/STP Task/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace STP_Task.Models
{
    public class RegisterViewModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConfirmP { get; set; }
    }
}

STP Task/STP Task/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Contracts;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using STP_Task.Models;

namespace STP_Task.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService cService;
        private readonly IEmployeeService eService;

        public CompanyController(ICompanyService companyService, IEmployeeService employeeService)
        {
            this.cService = companyService;
            this.eService = employeeService;
        }

        public IActionResult Index()
        {
            var vm = new CompanySearchViewModel();
            return View(vm);
        }

        public async Task<IActionResult> DisplaySearchResults(string keyword, string page)
        {
            var model = new CompanySearchResultsViewModel()
            {
                Keyword = keyword,
                Searched = true
            };

            if (model.Keyword == null)
            {
                model.Keyword = "";
            }

            model.Page = int.Parse(page);
            Tuple<IList<Company>, bool> tuple;
            tuple = await cService.SearchCompanyByNameAsync(model.Keyword, model.Page);

            IList<Company> companies = tuple.Item1;
            foreach (var template in companies)
            {
                model.Companies.Add(new CompanyViewModel(template));
            }
            model.LastPage = tuple.Item2;
            return PartialView("_SearchResults", model);
        }

        [HttpGet]
        public IActionResult AddCompany()
        {
            var vm = new CompanyViewModel();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> AddCompany(CompanyViewModel vm)
        {
            await cService.AddCompanyAsync(vm.Name, vm.CreationDate);
            var vm1 = new CompanySearchViewModel();
            return View("Index", vm1);
        }

        public async Task<IActionResult> AddOffice(CompanyEditViewModel vm)
        {
            await cService.AddOfficeAsync(vm.NewOfficeCountry, vm.NewOfficeCity, vm.NewOfficeStreet, vm.NewOfficeStreetNumber, vm.Id);
            var company = await cService.FindCompanyByIdAsync(vm.Id);
            var vm1 = new CompanyEditViewModel(company, company.Offices.ToList());
            return View("EditCompany", vm1);
        }

        public async Task<IActionResult> RemoveOffice(string submitButton)
        {
            var id = await cService.RemoveOfficeAsync(int.Parse(submitButton));
            var company = await cService.FindCompanyByIdAsync(id);
            var vm1 = new CompanyEditViewModel(company, company.Offices.ToList());
            return View("EditCompany", vm1);
        }

        public async Task<IActionResult> AssignHeadquarter(string submitButton)
        {
            var id = await cService.AssignHeadquarters(int.Parse(submitButton));
            var company = await cService.FindCompanyByIdAsync(id);
            var vm1 = new CompanyEditViewModel(company, company.Offices.ToList());
            return View("EditCompany", vm1);
        }

        public async Task<IActionResult> UnassignHeadquarter(string submitButton)
        {
            var id = await cService.UnassignHeadquarters(int.Parse(submitButton));
            var company = await cService.FindCompanyByIdAsync(id);
            var vm1 = new CompanyEditViewModel(company, company.Offices.ToList());
            return View("EditCompany", vm1);
        }

        public async Task<IActionResult> GetEditCompany(string submitButton)
        {
            var company = await cService.FindCompanyByIdAsync(int.Parse(submitButton));
            var vm = new CompanyEditViewModel(company, company.Offices.ToList());
            return View("EditCompany", vm);
        }

        public async Task<IActionResult> EditCompany(CompanyEditViewModel vm)
        {
            await cService.EditCompany(vm.Id, vm.Name);
            var company = await cService.FindCompanyByIdAsync(vm.Id);
            var vm1 = new CompanyEditViewModel(company, company.Offices.ToList());
            return View("EditCompany", vm1);
        }

        public async Task<IActionResult> RemoveCompany(string submitButton)
        {
            await cService.RemoveCompanyAsync(int.Parse(submitButton));
            var vm = new CompanySearchViewModel();
            return View("Index", vm);
        }

        public async Task<IActionResult> GetOfficeAssigning(string submitButton)
        {
            var office = await cService.GetOfficeAsync(int.Parse(submitButton));
            var vm = new OfficeViewModel(office);
            return View("OfficeAssigning", vm);
        }

        public async Task<IActionResult> GetEmployeesForOffice(string keyword)
        {
            var employees = await eService.GetOfficeEmployeesAsync(int.Parse(keyword));
            var vm = new OfficeAssigningViewModel(employees);
            return PartialView("_OfficeAssigning", vm);
        }
        [HttpPost]
        public async Task<IActionResult> AssignEmployee(string eId, string oId)
        {
            await eService.AssignEmployeeAsync(int.Parse(eId), int.Parse(oId));
            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> UnassignEmployee(string eId, string oId)
        {
            await eService.UnassignEmployeeAsync(int.Parse(eId));
            return Ok();
        }
    }
}

STP Task/STP Task/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using STP_Task.Models;

namespace STP_Task.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService eService;
        public EmployeeController(IEmployeeService eService)
        {
            this.eService = eService;
        }

        public IActionResult Index()
        {
            var vm = new EmployeeSearchViewModel();
            return View(vm);
        }

        public async Task<IActionResult> DisplaySearchResults(string keyword, string page)
        {
            var model = new EmployeeSearchResultsViewModel()
            {
                Keyword = keyword,
                Searched = true
            };

            if (model.Keyword == null)
            {
                model.Keyword = "";
            }

            model.Page = int.Parse(page);
            Tuple<IList<Employee>, bool> tuple;
            tuple = await eService.SearchEmployeeByNameAsync(model.Keyword, model.Page);

            IList<Employee> employees = tuple.Item1;
            foreach (var template in employees)
            {
                model.Employees.Add(new EmployeeViewModel(template));
            }
            model.LastPage = tuple.Item2;
            return PartialView("_SearchResults", model);
        }

        public async Task<IActionResult> GetEditEmployee(string submitButton)
        {
            var employee = await eService.GetEmployeeAsync(int.Parse(submitButton));
            var vm = new EmployeeEditViewModel(employee);
            return View("EditEmployee", vm);
        }
        public async Task<IActionResult> EditEmployee(EmployeeEditViewModel vm)
        {
            await eService.EditEmployeeAsync(vm.Id, vm.FirstName, vm.LastName, vm.Salary, vm.VacationDays, byte.Parse(vm.ExperienceLevel));
            var vm1 = new EmployeeSearchViewModel();
            return View("Index", vm1);
        }

        [HttpGet]
        public IActionResult AddEmployee()
        {
            var vm = new EmployeeViewModel();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> AddEmployee(EmployeeViewModel vm)
        {
            await eService.AddEmployeeAsync(vm.FirstName, vm.LastName, vm.StartingDate, vm.Salary, vm.VacationDays, byte.Parse(vm.ExperienceLevel));
            var vm1 = new EmployeeSearchViewModel();
            return View("Index", vm1);
        }

        public async Task<IActionResult> RemoveEmployee(string submitButton)
        {
            await eService.RemoveEmployeeAsync(int.Parse(submitButton));
            var vm1 = new EmployeeSearchViewModel();
            return View("Index", vm1);
        }

    }
}

STP Task/STP Task/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Data.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using STP_Task.Models;

namespace STP_Task.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAccountService aService;
        public HomeController(IAccountService accountService)
        {
            this.aService = accountService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult ViewLogin()
        {
            var vm = new LoginViewModel();
            return PartialView("_Login", vm);
        }

        public IActionResult ViewRegister()
        {
            var vm = new RegisterViewModel();
            return PartialView("_Register", vm);
        }

        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            if (!this.ModelState.IsValid)
                return View("Login", vm);

            try
            {
                var user = await this.aService.AttemptUserLoginAsync(vm.Username, vm.Password);
                SignInUser(user);
            }
            catch (Exception ex) { }
            return ReturnHome();
        }
        public async Task<IActionResult> Register(RegisterViewModel vm)
        {
            if (!this.ModelState.IsValid)
                return View("_Register", vm);
            try
            {
                if (vm.Password == vm.ConfirmP && vm.Password.Length >= 6)
                {
                    await this.aService.AddAccountAsync(vm.Username, vm.Password);
                    var user = await aService.AttemptUserLoginAsync(vm.Username, vm.Password);
                    SignInUser(user);
                }
                else
                {
                    return View("_Register", vm);
                }
                return ReturnHome();
            }
            catch (Exception)
            {
                return ReturnHome();
            }
        }
        public async Task<IActionResult> CheckIfUsernameAvailable(string username)
        {
            try
            {
                var user = await aService.FindUserByUserNameAsync(username);
            }
            catch (Exception)
            {
                return Json("available");
            }
            return Json("unavailable");
        }

        public async Task<IActionResult> Logout()
        {
            await this.HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return ReturnHome();
        }

        private async void SignInUser(User user)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())
            };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddHours(24),
                IssuedUtc = DateTimeOffset.UtcNow,
                IsPersistent = true,
            };

            await this.HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
        }
        private RedirectToActionResult ReturnHome()
          => RedirectToAction("Index", "Home");

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

STP Task/STP Task/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="home-main">
    @if (User.Identity.IsAuthenticated)
    {
        <div class="container">
            <div class="row">
                <div class="col-4"></div>
                <div class="col-4">
                    <ul class="nav flex-column">
                        <li class="btn btn-sm btn-outline-secondary">
                            <a class="nav-link" style="color:deepskyblue;font-size: 20px" asp-area="" asp-controller="Company" asp-action="Index">
                                Browse Company List
                            </a>
                        </li>
                        <li class="btn btn-sm btn-outline-secondary">
                            <a class="nav-link" style="color:deepskyblue;font-size: 20px" asp-area="" asp-controller="Employee" asp-action="Index">
                                Browse Employee List
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-4"></div>
            </div>
        </div>
    }
</div>

@if (!User.Identity.IsAuthenticated)
{
    <script src="~/js/NotAuthenticatedIndex.js"></script>

}

STP Task/STP Task/Views/Home/_Login.cshtml
@model LoginViewModel

<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4 text-center">
            <h3>
                Please log in to proceed
            </h3>
            <form class="form" role="form" method="post" asp-action="Login" asp-controller="Home">
                <div class="form-group">
                    <label class="control-label">Username</label>
                    <input type="text" class="form-control" asp-for="@Model.Username" placeholder="Enter Username">
                </div>
                <div class="form-group">
                    <label class="control-label">Password</label>
                    <input type="password" class="form-control" asp-for="@Model.Password" placeholder="Enter Password">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Sign In</button>&nbsp;
                    <button type="reset" class="btn btn-primary btn-inverse">Reset</button>
                </div>
            </form>
            if you dont have an account you can <a href="#" onclick="Register()">register</a>
        </div>
        <div class="col-4"></div>
    </div>
</div>

STP Task/STP Task/Views/Home/_Register.cshtml
@model RegisterViewModel

<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4 text-center">
            <h3>
                Account Registration
            </h3>
            <form class="form" role="form" method="post" asp-action="Register" asp-controller="Home">
                <div class="form-group">
                    <label class="control-label">Username</label>
                    <input type="text" class="form-control" asp-for="@Model.Username" oninput="checkIfFree(this.value)" placeholder="Enter Username">
                    <span id="username-validation" hidden="hidden" style="color: red;" class="text-danger">Username is already taken</span>
                </div>
                <div class="form-group">
                    <label class="control-label">Password</label>
                    <input type="password" class="form-control" asp-for="@Model.Password" oninput="checkIfPassConfirmed()" id="password" placeholder="Enter Password">
                    <span id="password-length" hidden="hidden" style="color: red;" class="text-danger">Password must be at least 6 characters long</span>
                </div>
                <div class="form-group">
                    <label class="control-label">Confirm Password</label>
                    <input type="password" class="form-control" asp-for="@Model.ConfirmP" oninput="checkIfPassConfirmed()" id="password-confirm" placeholder="Enter Password again">
                    <span id="password-validation" hidden="hidden" style="color: red;" class="text-danger">Passwords do not match</span>
                </div>
                <div class="form-group">
                    <!-- Button -->
                    <button type="submit" class="btn btn-primary" id="register-button" disabled>Register</button>&nbsp;
                    <button type="reset" class="btn btn-primary btn-inverse">Reset</button>
                </div>
            </form>
            return to <a href="#" onclick="Login()">login</a>
        </div>
        <div class="col-4"></div>
    </div>
</div>

<script src="~/js/Register.js"></script>